apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test-app"
  tags:
    - ssc
    - nodejs
    - sbom 
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
