apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-app 
  name: test-app
  namespace: test-app 
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: test-app 
